services:
  frontend:
    image: jihyun923/group-diary-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  backend:
    image: jihyun923/group-diary-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    restart: always